stages:
- deploy



deploy:

  stage: deploy

  only:
  - master

  script:
  - cp -rT ./cogs/ /srv/bot/discord-ninja-python/cogs
  - cp -rT ./utils/ /srv/bot/discord-ninja-python/utils

only:
  changes:
  - cogs/*.py
  - utils/*.py
